In [1]:
from keras.layers import Input, Dense, Lambda, Flatten, Activation, Merge, Concatenate, Add
from keras import layers
from keras.layers.merge import concatenate
from keras.models import Model, Sequential
from keras.objectives import binary_crossentropy
from keras.callbacks import LearningRateScheduler

import numpy as np
from scipy.stats import sem
from keras import backend as K
from keras.models import load_model
import tensorflow as tf


from models import vgg
from models.cvae import CVAE
from models.cvae_mod import CVAE as CVAE_mod
from utils.losses import von_mises_log_likelihood_np
from utils.angles import deg2bit, bit2deg, bit2deg_multi
from utils.losses import mad_loss_tf, cosine_loss_tf, von_mises_loss_tf, maad_from_deg
from utils.losses import gaussian_kl_divergence_tf, gaussian_kl_divergence_np
from utils.losses import gaussian_log_likelihood_np, gaussian_log_likelihood_scipy, gaussian_log_likelihood_tf
from utils.losses  import von_mises_log_likelihood_tf, von_mises_log_likelihood_np
from utils.losses import maximum_expected_utility
from utils.towncentre import load_towncentre, aug_data
from utils.experiements import get_experiment_id

Using TensorFlow backend.


#### Loading dataset

In [2]:
xtr, ytr_deg, xval, yval_deg, xte, yte_deg = load_towncentre('data/TownCentre.pkl.gz', canonical_split=True, verbose=1)

image_height, image_width = xtr.shape[1], xtr.shape[2]

ytr_bit = deg2bit(ytr_deg)
yval_bit = deg2bit(yval_deg)
yte_bit = deg2bit(yte_deg)
yte_rad = np.deg2rad(yte_deg)

image_height, image_width, n_channels = xtr.shape[1:]
flatten_x_shape = xtr[0].flatten().shape[0]
phi_shape = yte_bit.shape[1]

Number of train samples: 6916
Number of validation samples: 874
Number of test samples: 904


#### Loading pre-trained models

#### Biternion-VGG (cosine-loss)

In [3]:
vgg_cosine = vgg.BiternionVGG(image_height=image_height,
                              image_width=image_width,
                              n_channels=3,
                              predict_kappa=False,
                              fixed_kappa_value=3.0)

vgg_cosine.model.load_weights('../biternion_net_cluster_logs/best_models/cosine/vgg_bit_cosine_town.best.weights.h5')

results_cosine = dict()
results_cosine['train'] = vgg_cosine.evaluate(xtr, ytr_deg, 'train')
results_cosine['validation'] = vgg_cosine.evaluate(xval, yval_deg, 'validation')
results_cosine['test'] = vgg_cosine.evaluate(xte, yte_deg, 'test')

MAAD error (train) : 6.394312 ± 0.073692SEM
log-likelihood (train) : -0.456771 ± 0.001295SEM
MAAD error (validation) : 21.833931 ± 0.966800SEM
log-likelihood (validation) : -0.843196 ± 0.034713SEM
MAAD error (test) : 24.108348 ± 1.069605SEM
log-likelihood (test) : -0.926001 ± 0.038936SEM


#### Biternion-VGG (Von-Mises loss)

In [4]:
vgg_vm = vgg.BiternionVGG(image_height=image_height,
                          image_width=image_width,
                          n_channels=3,
                          predict_kappa=False,
                          fixed_kappa_value=3.0)

vgg_vm.model.load_weights('../biternion_net_cluster_logs/best_models/von_mises/vgg_bit_von_mises_town.best.weights.h5')

results_vm = dict()
results_vm['train'] = vgg_vm.evaluate(xtr, ytr_deg, 'train')
results_vm['validation'] = vgg_vm.evaluate(xval, yval_deg, 'validation')
results_vm['test'] = vgg_vm.evaluate(xte, yte_deg, 'test')

vm_preds = vgg_vm.model.predict(xte)
vm_preds_mu_rad = np.deg2rad(bit2deg(vm_preds))
vm_preds_kappa = np.ones([xte.shape[0],1])*3
vm_preds_likelihoods = von_mises_log_likelihood_np(yte_bit, vm_preds[:,0:2], vm_preds_kappa)

MAAD error (train) : 9.459415 ± 0.142856SEM
log-likelihood (train) : -0.510601 ± 0.004218SEM
MAAD error (validation) : 22.974047 ± 0.999363SEM
log-likelihood (validation) : -0.883493 ± 0.036697SEM
MAAD error (test) : 24.156092 ± 1.083819SEM
log-likelihood (test) : -0.925846 ± 0.039583SEM


#### Biternion-VGG (log-likelihood, fixed  $\kappa=3$ )

In [5]:
vgg_fixed_kappa = vgg.BiternionVGG(image_height=image_height,
                                   image_width=image_width,
                                   n_channels=3,
                                   predict_kappa=False,
                                   fixed_kappa_value=3.0)

vgg_fixed_kappa.model.load_weights('../biternion_net_cluster_logs/best_models/fixed_kappa/vgg_bit_vm_likelihood_town.best.weights.h5')

results_fixed = dict()
results_fixed['train'] = vgg_fixed_kappa.evaluate(xtr, ytr_deg, 'train')
results_fixed['validation'] = vgg_fixed_kappa.evaluate(xval, yval_deg, 'validation')
results_fixed['test'] = vgg_fixed_kappa.evaluate(xte, yte_deg, 'test')

fixed_preds = vgg_fixed_kappa.model.predict(xte)
fixed_preds_mu_rad = np.deg2rad(bit2deg(fixed_preds))
fixed_preds_kappa = np.ones([xte.shape[0],1])*3
fixed_preds_likelihoods = von_mises_log_likelihood_np(yte_bit, fixed_preds[:,0:2], fixed_preds_kappa)

MAAD error (train) : 11.216375 ± 0.144446SEM
log-likelihood (train) : -0.533973 ± 0.003843SEM
MAAD error (validation) : 22.728342 ± 0.990586SEM
log-likelihood (validation) : -0.870462 ± 0.035802SEM
MAAD error (test) : 24.155143 ± 1.088582SEM
log-likelihood (test) : -0.929270 ± 0.039672SEM


#### Biternion-VGG (log-likelihood loss, learned  $\kappa$ )

In [6]:
vgg_learned_kappa = vgg.BiternionVGG(image_height=image_height,
                                     image_width=image_width,
                                     n_channels=3,
                                     predict_kappa=True)

vgg_learned_kappa.model.load_weights('../biternion_net_cluster_logs/best_models/learned_kappa/vgg_bit_vm_likelihood_town.best.weights.h5')

results_learned = dict()
results_learned['train'] = vgg_learned_kappa.evaluate(xtr, ytr_deg, 'train')
results_learned['validation'] = vgg_learned_kappa.evaluate(xval, yval_deg, 'validation')
results_learned['test'] = vgg_learned_kappa.evaluate(xte, yte_deg, 'test')

learned_preds = vgg_learned_kappa.model.predict(xte)
learned_preds_mu_rad = np.deg2rad(bit2deg(learned_preds[:,0:2]))
learned_preds_kappa = learned_preds[:,2:]
learned_preds_likelihoods = von_mises_log_likelihood_np(yte_bit, learned_preds[:,0:2], learned_preds_kappa)

MAAD error (train) : 14.462390 ± 0.213100SEM
log-likelihood (train) : -0.203715 ± 0.010644SEM
MAAD error (validation) : 24.398405 ± 1.090128SEM
log-likelihood (validation) : -0.802889 ± 0.078568SEM
MAAD error (test) : 24.327137 ± 1.095842SEM
log-likelihood (test) : -0.764323 ± 0.066594SEM


#### CVAE model (normal training)

In [4]:
n_samples = 10
n_u = 8
cvae = CVAE(n_hidden_units=n_u)
cvae_ckpt_path = '../biternion_net_cluster_logs/best_models/cvae/original_trainining/cvae.full_model.trial_4.best.weights.hdf5'
cvae.full_model.load_weights(cvae_ckpt_path)

results_cvae = dict()
results_cvae['train'] = cvae.evaluate(xtr, ytr_deg, 'train')
results_cvae['validation'] = cvae.evaluate(xval, yval_deg, 'validation')
results_cvae['test'] = cvae.evaluate(xte, yte_deg, 'test')

cvae_preds = cvae.get_multiple_predictions(xte, yte_bit, n_samples=n_samples)

MAAD error (train) : 14.758449 ± 0.220159SEM
ELBO (train) : -0.201158 ± 0.008586SEM
KL-div (train) : 0.000010 ± 0.000002SEM
MAAD error (validation) : 23.260531 ± 1.041506SEM
ELBO (validation) : -0.608598 ± 0.041171SEM
KL-div (validation) : 0.000040 ± 0.000027SEM
MAAD error (test) : 26.120249 ± 1.185110SEM
ELBO (test) : -0.667623 ± 0.047162SEM
KL-div (test) : 0.000013 ± 0.000003SEM


In [133]:
def get_multiple_predictions(self, x, y_bit, n_samples=5):

        n_points = x.shape[0]

        mu_bit_preds = np.zeros([n_points, n_samples, 2])
        kappa_preds  = np.zeros([n_points, n_samples, 1])
        reconstruction_errs = np.zeros([n_points, n_samples, 1])
        kl_preds = np.zeros([n_points, n_samples, 1])
        elbo_preds = np.zeros([n_points, n_samples, 1])
        u_encoder = np.zeros([n_points, n_samples, self.n_u])

        mu_bit_preds_dec = np.zeros([n_points, n_samples, 2])
        kappa_preds_dec = np.zeros([n_points, n_samples, 1])

        for sid in range(0, n_samples):
            preds = self.full_model.predict([x, y_bit])
            mu_bit_preds[:, sid, :] = preds[:, self.n_u * 5:self.n_u * 5 + 2]
            u_encoder[:, sid, :] = preds[:, self.n_u*4:self.n_u*5]
            ###
            mu_encoder = preds[:, self.n_u*2:self.n_u*3]
            log_sigma_encoder = preds[:, self.n_u*3:self.n_u*4]
            ###
            kappa_preds[:, sid, :] = preds[:, self.n_u * 5 + 2:].reshape(-1, 1)
            elbo, reconstruction, kl = self._cvae_elbo_loss_np(y_bit, preds)
            reconstruction_errs[:, sid, :] = reconstruction
            kl_preds[:, sid, :] = kl
            elbo_preds[:, sid, :] = elbo
            preds_dec = self.decoder_model.predict(x, batch_size=100)
            mu_bit_preds_dec[:, sid, :] = preds_dec[:, 0:2]
            kappa_preds_dec[:, sid, :] = preds_dec[:, 2:].reshape(-1, 1)

        preds = dict()

        preds['mu_bit'] = mu_bit_preds
        preds['kappa'] = kappa_preds
        preds['mu_encoder'] = mu_encoder
        preds['log_sigma_encoder'] = log_sigma_encoder
        preds['u_encoder'] = u_encoder
        preds['reconstruction_err'] = reconstruction_errs
        preds['kl_div'] = kl_preds
        preds['elbo'] = elbo_preds
        preds['mu_bit_dec'] = mu_bit_preds_dec
        preds['kappa_dec'] = kappa_preds_dec
        preds['mu_rad_dec'] = np.deg2rad(bit2deg_multi(preds['mu_bit_dec']))
        preds['maxutil_deg_dec'] = maximum_expected_utility(np.rad2deg(preds['mu_rad_dec']))

        return preds

In [177]:
cvae = CVAE(n_hidden_units=n_u)
cvae_preds = get_multiple_predictions(cvae, xte, yte_bit, n_samples=3)

In [179]:
sampler = Model(inputs=[cvae.x, cvae.phi],
                     outputs=cvae.u_encoder)

In [245]:
n_u = 8

mu_in = Input(shape=[n_u])
log_sigma_in = Input(shape=[n_u])

def sample_u(args):
    mu, log_var = args
    eps = K.random_normal(shape=K.shape(mu), mean=0., stddev=1.)
    return mu*0 + eps
    #return mu + K.exp(log_var / 2) * eps

sampler = Lambda(sample_u)([mu_in, log_sigma_in])

sampler_model = Model(inputs=[mu_in, log_sigma_in],
                     outputs=sampler)

In [206]:
mu = np.zeros([2, n_u])
mu[0] = 1
mu[1] = 2
log_sigma = np.ones([2, n_u])*(-10)

In [241]:
sampler_model.output

<tf.Tensor 'lambda_44/add:0' shape=(2, 8) dtype=float32>

In [257]:
sampler_model.predict([mu, log_sigma])

array([[-0.02880593,  0.40664971, -0.77520287, -0.74658483,  0.84093112,
        -0.72485077, -1.06333017, -0.08272685],
       [-0.45024374, -2.06894732,  0.28424916,  1.25946736, -0.11047936,
        -1.6831249 , -0.36015663,  0.73252487]], dtype=float32)

In [184]:
cvae_preds['log_sigma_encoder'][0:10]

array([[-0.05707061, -0.00404783, -0.00977527, -0.02174146,  0.01336844,
        -0.02449911, -0.014545  , -0.04374285],
       [-0.05758778, -0.00497832, -0.00745558, -0.02146406,  0.01421839,
        -0.02259953, -0.00901022, -0.0374117 ],
       [-0.04984568, -0.00722014, -0.0122745 , -0.02466514,  0.00739885,
        -0.02222436, -0.00953719, -0.05041127],
       [-0.01313085, -0.02920785, -0.00591344,  0.00063484,  0.03920221,
        -0.01361689, -0.02337938, -0.02000741],
       [-0.01503917, -0.03090731, -0.0074629 ,  0.00314598,  0.03961475,
        -0.01469764, -0.02549474, -0.02414679],
       [-0.01972614, -0.03620252, -0.00665186,  0.0176758 ,  0.02376397,
        -0.01518471, -0.02521229, -0.02770213],
       [-0.02005113, -0.03645652, -0.00638025,  0.01756263,  0.02449874,
        -0.01572522, -0.02543916, -0.02755902],
       [-0.03592714, -0.03951794, -0.00779481,  0.03135096,  0.02035963,
        -0.01744977, -0.00176213, -0.0268246 ],
       [-0.05213824, -0.00628078

In [148]:
def _sample_u(args):
    mu, log_var = args
    eps = K.random_normal(shape=[n_u], mean=0., stddev=1.)
    return mu + K.exp(log_var / 2) * eps 

array([[ 0.35053813, -1.20484817, -1.1041975 , -0.08003835,  0.39555457,
        -0.43704724,  0.15992749,  0.13171601],
       [ 0.34460765, -1.21618259, -1.10574949, -0.07989436,  0.39270681,
        -0.43620652,  0.15336534,  0.13661955],
       [ 0.34460765, -1.21618259, -1.10574949, -0.07989436,  0.39270681,
        -0.43620652,  0.15336534,  0.13661955],
       [ 0.34460765, -1.21618259, -1.10574949, -0.07989436,  0.39270681,
        -0.43620652,  0.15336534,  0.13661955],
       [ 0.34460765, -1.21618259, -1.10574949, -0.07989436,  0.39270681,
        -0.43620652,  0.15336534,  0.13661955],
       [ 0.34460765, -1.21618259, -1.10574949, -0.07989436,  0.39270681,
        -0.43620652,  0.15336534,  0.13661955],
       [ 0.34460765, -1.21618259, -1.10574949, -0.07989436,  0.39270681,
        -0.43620652,  0.15336534,  0.13661955],
       [ 0.34460765, -1.21618259, -1.10574949, -0.07989436,  0.39270681,
        -0.43620652,  0.15336534,  0.13661955],
       [ 0.34460765, -1.21618259

In [ ]:
    def _sample_u(self, args):
        mu, log_var = args
        eps = K.random_normal(shape=[self.n_u], mean=0., stddev=1.)
        return mu + K.exp(log_var / 2) * eps

In [121]:
cvae_preds['u_encoder'][0,0,:]

array([ 0.90835947, -0.48239964,  0.87819713,  1.0777328 ,  0.97830355,
        0.91386724,  0.9272061 ,  0.37996763])

In [122]:
cvae_preds['u_encoder'][0,1,:]

array([ 0.17263976, -1.20098841, -0.14676139,  1.1406914 , -0.04492545,
       -0.45425573, -0.68363494, -0.90265632])

In [123]:
cvae_preds['u_encoder'][0:20,0,:]

array([[ 0.90835947, -0.48239964,  0.87819713,  1.0777328 ,  0.97830355,
         0.91386724,  0.9272061 ,  0.37996763],
       [ 0.91165006, -0.47549355,  0.88035733,  1.07755208,  0.98008364,
         0.9142611 ,  0.9307515 ,  0.37765816],
       [ 0.90835947, -0.48239964,  0.87819713,  1.0777328 ,  0.97830355,
         0.91386724,  0.9272061 ,  0.37996763],
       [ 0.90835947, -0.48239964,  0.87819713,  1.0777328 ,  0.97830355,
         0.91386724,  0.9272061 ,  0.37996763],
       [ 0.90835947, -0.48239964,  0.87819713,  1.0777328 ,  0.97830355,
         0.91386724,  0.9272061 ,  0.37996763],
       [ 0.90835947, -0.48239964,  0.87819713,  1.0777328 ,  0.97830355,
         0.91386724,  0.9272061 ,  0.37996763],
       [ 0.90835947, -0.48239964,  0.87819713,  1.0777328 ,  0.97830355,
         0.91386724,  0.9272061 ,  0.37996763],
       [ 0.90835947, -0.48239964,  0.87819713,  1.0777328 ,  0.97830355,
         0.91386724,  0.9272061 ,  0.37996763],
       [ 0.90835947, -0.48239964

In [126]:
cvae_preds['mu']

KeyError: 'mu_encoder'

In [118]:
cvae_preds['u_encoder'].shape

(904, 2, 8)

#### CVAE model (KL annealing)

In [52]:
n_u = 8
cvaekl = CVAE(n_hidden_units=n_u)
cvaekl_ckpt_path = '../biternion_net_cluster_logs/best_models/cvae/kl_annealing/cvae.full_model.trial_1.best.weights.hdf5'
cvaekl.full_model.load_weights(cvaekl_ckpt_path)

results_cvaekl = dict()
results_cvaekl['train'] = evaluate_multi(xtr, ytr_deg, 'train')
results_cvaekl['validation'] = evaluate_multi(cvaekl, xval, yval_deg, 'validation', n_samples=n_samples)
results_cvaekl['test'] = evaluate_multi(cvaekl, xte, yte_deg, 'test', n_samples=n_samples)

#cvaekl_mu_bit_preds, cvaekl_kappa_preds = cvaekl.generate_multiple_samples(xte)
cvaekl_preds = cvaekl.get_multiple_predictions(xte, yte_bit, n_samples=n_samples)

MAAD error (test) : 25.375051 ± 1.176808SEM
ELBO (test) : -0.729948 ± 0.056895SEM
KL-div (test) : 0.206518 ± 0.015021SEM


#### CVAE model (augmentation with opposite angles)

In [65]:
n_u = 8
cvaeaug = CVAE(n_hidden_units=n_u)
cvaeaug_ckpt_path = '../biternion_net_cluster_logs/best_models/cvae/opposite_labels_aug/cvae.full_model.trial_0.best.weights.hdf5'
cvaeaug.full_model.load_weights(cvaeaug_ckpt_path)

xtr_aug, ytr_aug_deg = aug_data(xtr, ytr_deg)
xval_aug, yval_aug_deg = aug_data(xval, yval_deg)
xte_aug, yte_aug_deg = aug_data(xte, yte_deg)
ytr_aug_bit = deg2bit(ytr_aug_deg)
yval_aug_bit = deg2bit(yval_aug_deg)
yte_aug_bit = deg2bit(yte_aug_deg)

results_cvaeaug = dict()
results_cvaeaug['train'] = cvaeaug.evaluate(xtr_aug, ytr_aug_deg, 'train')
results_cvaeaug['validation'] = cvaeaug.evaluate(xval_aug, yval_aug_deg, 'validation')
results_cvaeaug['test'] = cvaeaug.evaluate(xte_aug, yte_aug_deg, 'test')

cvaeaug_preds = cvaekl.get_multiple_predictions(xte, yte_bit, n_samples=n_samples)

MAAD error (train) : 89.978635 ± 0.551583SEM
ELBO (train) : -3.587595 ± 0.024828SEM
KL-div (train) : 0.000981 ± 0.000025SEM
MAAD error (validation) : 90.165400 ± 1.516843SEM
ELBO (validation) : -3.490701 ± 0.066569SEM
KL-div (validation) : 0.001268 ± 0.000082SEM
MAAD error (test) : 89.923780 ± 1.491162SEM
ELBO (test) : -3.530247 ± 0.066768SEM
KL-div (test) : 0.001393 ± 0.000093SEM


In [136]:
from utils.losses import log_bessel_approx_np

def vm_pdf(vals, mu_rad, kappa):
    return np.exp(kappa * np.cos(vals-mu_rad)) / (2* np.pi * np.exp(log_bessel_approx_np(kappa)))

import matplotlib.pyplot as plt
%matplotlib inline


def plot_vm_dists(fid):
    x_vals = np.arange(0, 2*np.pi, 0.01)
    
    fig, axs = plt.subplots(1, 7, figsize=(25, 5))
    
    axs[0].imshow(xte[fid])
    
    def _plt_vgg(axis, mu_rad_preds, kappa_preds, log_likelihoods, method_name):
        axis.set_xticks(([0., .5*np.pi, np.pi, 1.5*np.pi, 2*np.pi]))
        axis.set_xticklabels(["$0$", r"$\frac{\pi}{2}$", r"$\pi$", r"$\frac{3\pi}{2}$", r"$2\pi$"]) 
        axis.set_xlim([-0.001, 2*np.pi+0.001])
        axis.plot(x_vals, np.squeeze(vm_pdf(x_vals, mu_rad_preds[fid], kappa_preds[fid])))
        axis.axvline(yte_rad[fid], color='red')
        axis.set_title("%s (logL=%.2f)" % (method_name, log_likelihoods[fid]))
        axis.set_ylim([0, 2.0])
        
    def _plt_cvae(axis, cvae_mu_rad_preds, cvae_kappa_preds, method_name, plot_mixture=False):
        axis.set_xticks(([0., .5*np.pi, np.pi, 1.5*np.pi, 2*np.pi]))
        axis.set_xticklabels(["$0$", r"$\frac{\pi}{2}$", r"$\pi$", r"$\frac{3\pi}{2}$", r"$2\pi$"]) 
        axis.set_xlim([-0.001, 2*np.pi+0.001])
        vm_vals = np.zeros([n_samples, x_vals.shape[0]])
        if plot_mixture:
            for sid in range(0, n_samples):
                vm_vals[sid, :] = vm_pdf(x_vals, cvae_mu_rad_preds[fid, sid], cvae_kappa_preds[fid, sid])
            axis.plot(x_vals, np.mean(vm_vals, axis=0))
        else:
            for sid in range(0, n_samples):
                axis.plot(x_vals, np.squeeze(vm_pdf(x_vals, cvae_mu_rad_preds[fid, sid], cvae_kappa_preds[fid, sid])))  
        axis.axvline(yte_rad[fid], color='red')
        axis.set_title("%s " % method_name)
        axis.set_ylim([0, 2.0])
        
    _plt_vgg(axs[1], vm_preds_mu_rad, vm_preds_kappa, vm_preds_likelihoods, 'original (Von-Mises loss)')
    _plt_vgg(axs[2], fixed_preds_mu_rad, fixed_preds_kappa, fixed_preds_likelihoods,  'fixed kappa')
    _plt_vgg(axs[3], learned_preds_mu_rad, learned_preds_kappa, learned_preds_likelihoods, 'learned kappa')
    _plt_cvae(axs[4], cvae_preds['mu_rad_dec'], cvae_preds['kappa_dec'], "CVAE (normal)")
    _plt_cvae(axs[5], cvaekl_mu_rad_preds,  cvaekl_kappa_preds, "CVAE (KL annealing)")
    _plt_cvae(axs[6], cvaekl_mu_rad_preds, cvaekl_kappa_preds, "CVAE (KL annealing, mixture density)", plot_mixture=True)
    # _plt_cvae(axs[7], cvaeaug_mu_rad_preds,  cvaeaug_kappa_preds, "CVAE (Random labels augmentation)")
    # _plt_cvae(axs[8], cvaeaug_mu_rad_preds, cvaeaug_kappa_preds, "CVAE (Random labels augmentation, mixture density)", plot_mixture=True)
    fig.suptitle("frame id =%d" %fid)
    #plt.plot((ytr_deg, x2), (y1, y2), 'k-')
    plt.show()

In [54]:
import time 

n_samples = 10

for fid in range(0, 10):
    plot_vm_dists(fid)

NameError: name 'plot_vm_dists' is not defined